Installer Fix for PyCharm Educational Edition
Munki couldn’t distinguish between PyCharm CE and PyCharm Educational.
This specific install check corrects this issue. Not all girls grok
Xcode.

diff --git a/catalogs/sgs-catalog b/catalogs/sgs-catalog
--- a/catalogs/sgs-catalog
+++ b/catalogs/sgs-catalog
@@ -593,11 +593,11 @@
 		<key>display_name</key>
 		<string>TextWrangler Programmers Editor</string>
 		<key>installer_item_hash</key>
-		<string>52eb092165f86a7a6faddd9b97c75f9781ef13462fcdf9a16d919960db8613a8</string>
+		<string>f25ce90a54570ee4fe2287cdbe5c8b2a57188423a3693becacfa0533f02e0aa2</string>
 		<key>installer_item_location</key>
-		<string>apps/barebones/TextWrangler_4.5.10.dmg</string>
+		<string>apps/barebones/TextWrangler_4.5.12.dmg</string>
 		<key>installer_item_size</key>
-		<integer>9659</integer>
+		<integer>9656</integer>
 		<key>installer_type</key>
 		<string>copy_from_dmg</string>
 		<key>installs</key>
@@ -608,9 +608,9 @@
 				<key>CFBundleName</key>
 				<string>TextWrangler</string>
 				<key>CFBundleShortVersionString</key>
-				<string>4.5.10</string>
+				<string>4.5.12</string>
 				<key>CFBundleVersion</key>
-				<string>3392</string>
+				<string>3398</string>
 				<key>minosversion</key>
 				<string>10.6.8</string>
 				<key>path</key>
@@ -639,7 +639,7 @@
 		<key>uninstallable</key>
 		<true/>
 		<key>version</key>
-		<string>4.5.10</string>
+		<string>4.5.12</string>
 	</dict>
 	<dict>
 		<key>RestartAction</key>
@@ -1068,6 +1068,28 @@
 		<string>PyCharm Educational Edition</string>
 		<key>display_name</key>
 		<string>PyCharm Educational Edition</string>
+		<key>installcheck_script</key>
+		<string>#!/bin/bash
+
+VER_FILE="/Applications/PyCharm Educational.app/Contents/Info.plist"
+
+VER_CHK="1.0.1"
+
+if [ -s "${VER_FILE}" ]; then
+	VERSION="`grep Copyright \"${VER_FILE}\" | awk '{print $4}' | cut -d\, -f1`"
+	# echo "Found version: ${VERSION}"
+	if [ ${VERSION:-0} \&lt; ${VER_CHK} ]; then
+		# echo "Needs update to ${VER_CHK}"
+		exit 0
+	else
+		# echo "${VER_CHK} currently installed"
+		exit 1
+	fi
+else
+	# echo "Missing ${VER_FILE}"
+	exit 0
+fi
+</string>
 		<key>installer_item_hash</key>
 		<string>fedffd333b42bb43293ed08df3c463e961452c842dec8d72be37d419e30cfea6</string>
 		<key>installer_item_location</key>
